### PR TITLE
Parse Systemd Release Candidate Versions

### PR DESCRIPTION
**Pull request by blitz**
Our systemd version parser chokes on versions, such as "255-rc2". Switch to regex parsing so we can easily handle this as well.

### CODE REVIEW

**Comment by blitz** [comment]
@nikstur I've removed the regex dependency. Please check again.

@RaitoBezarius Do you know why the build box barfed on the force-push? I can't seem to get a rebuild. Also the 'Rebuild' button in the Buildbot UI does nothing. (PS. Can you look into #264?)

**Review by nikstur — APPROVED** [review]
This is very cursed and has less and less to do with sane versioning but I can live with it.

**Comment by blitz** [comment]
> This is very cursed and has less and less to do with sane versioning but I can live with it.

If you have more actionable advice, I'm happy to take it. :)

**Comment by nikstur** [comment]
> > This is very cursed and has less and less to do with sane versioning but I can live with it.
> 
> If you have more actionable advice, I'm happy to take it. :)

I don't and that's my problem 🫠

**Comment by RaitoBezarius** [comment]
I would at least put `Option` to avoid this typing trick to represent `minor` as `-1` for RCs?

**Pull request merged**
