### PR TITLE
treewide: 0.3.0 -> 0.4.1

### PR DESCRIPTION
**Pull request by nikstur**

### CODE REVIEW

**Comment by andresilva** [comment]
Will you update the tag to this commit when it's merged?

**Comment by nikstur** [comment]
> Will you update the v0.4.0 tag to this commit when it's merged?

No I don't thinks so. I don't think the version numbers here make a material difference.

**Comment by andresilva** [comment]
The reason I came here was because after I updated, `bootctl status` was still reporting lanzastub 0.3.0.

**Comment by RaitoBezarius** [comment]
Let's at release a 0.4.1 with the right tags.

**Review by RaitoBezarius — APPROVED** [review]

**Comment by nikstur** [comment]
Some of these builds (also in other PRs) seem to be stuck at creating the `nixos-disk-image`.

**Comment by nikstur** [comment]
> Let's, at least, release a 0.4.1 with the right tags.

Done. https://github.com/nix-community/lanzaboote/releases/tag/v0.4.1

**Pull request merged**
