### PR TITLE
fix(tool): better error if public key is missing

### PR DESCRIPTION
**Pull request by Mic92**
Old:                                                                                                                                                        
                                                                                                                                                            
building the system configuration...                                                                                                                        
Installing Lanzaboote to "/boot"...                                                                                                                         
Failed to install generation.: No such file or directory (os error 2)                                                                                       
Failed to install bootloader                                                                                                                                
warning: error(s) occurred while switching to the new configuration                                                                                         
                                                                                                                                                            
New:                                                                                                                                                        
                                                                                                                                                            
building the system configuration...                                                                                                                        
Installing Lanzaboote to "/boot"...                                                                                                                         
Failed to install generation 1: Get stub name: Read public key '/etc/secureboot/keys/db/db.pem': No such file or directory (os error 2)                     
Failed to install bootloader                                                                                                                                
warning: error(s) occurred while switching to the new configuration

### CODE REVIEW

**Comment by Mic92** [comment]
Turns out that switching to overlay mounts also wiped my lanzaboote key.

**Comment by blitz** [comment]
@Mic92 I love the error messages! Any idea what happened to the CI?

**Review by blitz — APPROVED** [review]

**Comment by Mic92** [comment]
@blitz we just upgraded our CI server in nix-community and looks like the database state was discarded. Hopefully nix-community now works more stable overall, so I can remove my own buildbot eventually.

**Comment by kuflierl** [comment]
Love the much clearer error message. I am also working on a similar part with #384

**Pull request merged**
