### PR TITLE
docs: suggest to track released versions rather than master 

### PR DESCRIPTION
**Pull request by RaitoBezarius**
The flake setup previously suggested master implicitly, we use the latest known release.

### CODE REVIEW

**Comment by nikstur** [comment]
Thanks!

**Comment by dcarosone** [comment]
Oops.  This put the branch on the nixpkgs url, when it should have been on the lanzaboote url.

**Comment by nikstur** [comment]
Reverted in https://github.com/nix-community/lanzaboote/pull/210

**Comment by RaitoBezarius** [comment]
Thank you… *should not send PRs tired*

**Pull request merged**
