### PR TITLE
tool: atomically write to ESP

### PR DESCRIPTION
**Pull request by nikstur**
To minimize the potential for irrecoverable errors, only atomic writes to the ESP are performed. This is implemented by first copying the file to the destination with a `.tmp` suffix and then renaming it to the final desintation. This is atomic because the rename operation is atomic on POSIX platforms.

~~Specifically, this means that even if the system crashes during the operation, the final desintation path will **always** be intact if it exists at all.~~
Specifically, this means that even if the system crashes during the operation, the final desintation path will most likely be intact if it
exists at all. There are some nuances to this however. It **cannot** be actually guaranteed that the operation was performed on the filesystem level. However, this is the best we can do for now.

For reference:
- POSIX rename(2): https://pubs.opengroup.org/onlinepubs/9699919799/
- Rust fs::rename corresponds to rename(2) on Unix: https://doc.rust-lang.org/std/fs/fn.rename.html
- Rust fs::rename is implemented using libc's rename: https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/fs.rs#L1397
- Renaming in libc is atomic: https://www.gnu.org/software/libc/manual/html_node/Renaming-Files.html

Implements #80

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
> Specifically, this means that even if the system crashes during the operation, the final desintation path will always be intact if it exists at all.

Not really,

> But... if you are asking for consistency and atomicity at filesystem
level (e.g. you turn off disk / power supply during rename operation)
then this is not atomic and probably it cannot be implemented. When FAT
filesystem is mounted (either by Windows or Linux kernel) it is marked
by "dirty" flag and later when doing unmount, "dirty" flag is cleared.

It is possible for the rename to not be atomic at the underlying filesystem level, but can be atomic at the VFS level of the kernel.

Therefore, this operation can still be "unatomic" for our purpose, moreover, inconsistency might not be detected properly by UEFI firmwares because their FAT implementation... is subpar.

In all the cases, this PR is probably the best we can do, but I would advise to formulate the guarantees with precision.

**Comment by nikstur** [comment]
That sentence is kinda straight out of the libc docs (which the rust-stdlib uses):  

> One useful feature of rename is that the meaning of newname changes “atomically” from any previously existing file by that name to its new meaning (i.e., the file that was called oldname). There is no instant at which newname is non-existent “in between” the old meaning and the new meaning. If there is a system crash during the operation, it is possible for both names to still exist; but newname will always be intact if it exists at all. 

https://www.gnu.org/software/libc/manual/html_node/Renaming-Files.html

Regardless, I'll revise the message, weakening the promise. 

> A better implementation is to have a static ESP and have a journaled filesystem for critical files.

Reading boot files from any filesystem but FAT32 however would mean that we need filesystem drivers in the bootloader. That's why systemd-boot doesn't support anyting but FAT32 (because they can use the FS implementation of UEFI).

**Comment by RaitoBezarius** [comment]
> That sentence is kinda straight out of the libc docs (which the rust-stdlib uses):
> 
> > One useful feature of rename is that the meaning of newname changes “atomically” from any previously existing file by that name to its new meaning (i.e., the file that was called oldname). There is no instant at which newname is non-existent “in between” the old meaning and the new meaning. If there is a system crash during the operation, it is possible for both names to still exist; but newname will always be intact if it exists at all.

I don't think libc can provide such guarantees without collaboration from the kernel and the mailing list stuff I posted in the original issue are people from the Linux kernel saying this is impossible to uphold for FAT32, but should be possible for journaled filesystem, which makes sense.

> Regardless, I'll revise the message, weakening the promise.
> 
> > A better implementation is to have a static ESP and have a journaled filesystem for critical files.
> 
> Reading boot files from any filesystem but FAT32 however would mean that we need filesystem drivers in the bootloader. That's why systemd-boot doesn't support anyting but FAT32 (because they can use the FS implementation of UEFI).

> For systems where the firmware is able to read file systems directly, the ESP must — and the MBR boot and GPT XBOOTLDR partition should — be a file system readable by the firmware. For most systems this means VFAT (16 or 32 bit). Applications accessing both partitions should hence not assume that fancier file system features such as symlinks, hardlinks, access control or case sensitivity are supported.

Using XBOOTLDR partition (which sd-boot supports) can provide something here, but uncertain.

**Review by blitz — APPROVED** [review]
Looks like a clear improvement to before, even with the questions around atomicity.

**Comment by blitz** [comment]
I like the nice function documentation, btw.

**Comment by nikstur** [comment]
To be fair, the people from the mailing list didn't seem to be so sure themselves. :D

My understanding is that systemd-boot only uses the firmware/UEFI drivers to read any partition, incl. XBOOTLDR. So we should only really expect vFAT. The arch wiki suggests that too:

> systemd-boot does not do a file system check like it does for the ESP. Hence, it is possible to use any file system that your UEFI implementation can read.

https://wiki.archlinux.org/title/systemd-boot

Regardless, I weakened the guarantee and added a disclaimer in the commit message.
And in any case this is a good thread to refer to if the issue ever comes up again or we want to improve on it.

**Pull request merged**
