### PR TITLE
uboot: init

### PR DESCRIPTION
**Pull request by RaitoBezarius**
Opened as a very early draft to get the subcommands design right.

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Commit of interest: https://github.com/nix-community/lanzaboote/pull/197/commits/a6aadd0cc37787139f70d634c26f837226d798ba

**Comment by blitz** [comment]
Looks ok by me!

**Comment by nikstur** [comment]
I have a few general considerations. I see a few different things we can do to implement a multi-backend feature for lzbt. We can:

1. Turn most of lzbt into a re-usable library (which we also export to crates.io). Offer a very slim lzbt which wraps this library ONLY for systemd-boot. We do not offer a binary for any other backend but make it easy for others to implement their own. This would allow us to focus on the most important backend without being bogged down by supporting things we (or the world) doesn't care about (like Grub).

2. Offer multiple binaries in-tree (via build-time features or as actually different binaries declared in Cargo.toml). If we combine this with making the rest of the code more generic, we could appoint code owners for the binaries (and kinda igore the broken binaries if the code owners don't maintain them). We can still make these separate binaries feel like subcommands (like Git does it).

3. Turn lzbt into a "fat" installer that can install all sorts of backends via subcommands. This leaves all the maintenance burden with us because we cannot really allow code paths or subcommands that do not work. This is what you are proposing.

As you can see, I'm quite worried about bloating up lzbt and then standing there with no one maintaining it (like it happend with Grub everywhere).

I think there is value in being able to build a binary for only the required backend without all the other backend support (so bascially make the decision for the backend at build time instead of at runtime). Overall, I'm prefer something between option 1 and 2 because I also see value in maintaining the backends in-tree.

**Comment by nikstur** [comment]
Yes, let's go ahead with 2. Factoring out a re-usable library is something we can always do (and probably should) but are in no rush if we keep everything in-tree. Most sensible thing is then probably to start factoring lzbt-systemd-boot into its own binary so we can then add a second one next to it in a straightfoward way.

**Comment by RaitoBezarius** [comment]
Anyway, it's using another flake input, so the CI will have woes until I rebase that flake input myself.

**Pull request closed without merging**
