### PR TITLE
add framework specific instructions

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by nikstur** [comment]
We should eventually factor this out of the quick start into a separate doc.

**Comment by blitz** [comment]
@nikstur Should we also add instructions on how to update the Secure Boot blacklist? We should probably automate this somehow.

**Comment by nikstur** [comment]
Yes we should. I think fwupd can update dbx somehow now.

**Comment by blitz** [comment]
> Yes we should. I think fwupd can update dbx somehow now.

#274

**Pull request merged**
