### PR TITLE
Revert back to crane

### PR DESCRIPTION
**Pull request by nikstur**
This reverts commit 59e3ebb19fdd3fd235d8275b008538a72872bad7, reversing changes made to 9f97a908e4059221d39c7b7d0906c88b9fcc9c9b.

### CODE REVIEW

**Review by RaitoBezarius — APPROVED** [review]

**Comment by RaitoBezarius** [comment]
(I didn't test it, please proceed carefully.)

**Review by RaitoBezarius — APPROVED** [review]

**Comment by RaitoBezarius** [comment]
Tested.

**Comment by Lyndeno** [comment]
I couldn't find any information on this change. Is there a specific reason this change was reverted? Just out of curiousity

**Comment by RaitoBezarius** [comment]
We decided to go back to crane because it's more appropriate for our
development needs, while the nixpkgs infra can be used for the nixpkgs code.

More subtle reasons can be found as such: people didn't really enjoy
bootstrapping a Windows toolchain to compile smol Rust binaries and
rightfully.

Le mar. 29 août 2023 à 00:40, Lyndon Sanche ***@***.***> a
écrit :

**Pull request merged**
