### PR TITLE
Move tests into separate file, add more structure to nix directory, and run nixpkgs-fmt & statix over everything

### PR DESCRIPTION
**Pull request by nikstur**
The flake was getting hard to work with because it's getting pretty long and was not formatted. I refactored the nix bits:

- Formatted everything with nixpkgs-fmt
- Applied suggestions from statix 
- Moved the module (lanzaboote.nix) and the package (uefi-run.nix) into corresponding subdirs in the nix directory 
- Moved the tests into a separate file in the nix subdirectory
- Added nixpkgs-fmt and statix to devShell 

Review  commit by commit

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
This will collide badly with #30 ; I am hesitant to ask you to rebase on this PR and we will merge them together (?).

**Comment by nikstur** [comment]
Does #31 currently work or are we still waiting on upstream changes? #31 also depends on #26 right?

**Comment by RaitoBezarius** [comment]
upstream support has arrived for #31 : https://nixpk.gs/pr-tracker.html?pr=207171

**Comment by RaitoBezarius** [comment]
> Does #31 currently work or are we still waiting on upstream changes? #31 also depends on #26 right?

It does depend on #26 only because it will be easier to deal with conflicts like this and #26 is supposed to be merged "very soon", then end user docs should follow easily and we can get to #31 then this refactor, or you can bake the refactor in #31.

**Review by RaitoBezarius — APPROVED** [review]
LGTM

**Pull request merged**
