### PR TITLE
Verify Kernel/Initrd Integrity using Blake3

### PR DESCRIPTION
**Pull request by blitz**
We currently only embed file names. While we _do_ check whether these files are then signed, an attacker can mix and match any signed kernel and initrd. To prevent this, we now also embed a Blake3 hash of kernel/initrd into lanzaboote.

The upside of this is that the initrd does not have to wrapped into a PE file for signing anymore, because we guarantee its integrity using the signed hash from lanzaboote.

The downside is that blake3 has doubled the size of the lanzaboote binary.

Review commit-by-commit to have less clutter.

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
> The downside is that blake3 has doubled the size of the lanzaboote binary.

Could you post current size? 140KB?
So on a 512MiB ESP, it would mean ~3744 generations of that stub (excluding the obvious initrd & kernel & other EFI binaries that must end up there.)

**Comment by blitz** [comment]
> > The downside is that blake3 has doubled the size of the lanzaboote binary.
> 
> Could you post current size? 140KB? So on a 512MiB ESP, it would mean ~3744 generations of that stub (excluding the obvious initrd & kernel & other EFI binaries that must end up there.)

228 KiB for me. We can probably shrink this with some upstream work or pick something smaller than blake3. It should be straight-forward to pick other hash functions.

**Comment by nikstur** [comment]
Let's get this merged. We can think about the tradeoff of speed vs binary size later. This is good enough for now.

**Review by nikstur — APPROVED** [review]

**Comment by blitz** [comment]
It seems `checks.x86_64-linux.specialisation-works` fails. Will debug.

**Comment by nikstur** [comment]
> It seems `checks.x86_64-linux.specialisation-works` fails. Will debug.

On my local checkout the test passes. Are you sure that it's not the build server acting up?

**Comment by blitz** [comment]
> > It seems `checks.x86_64-linux.specialisation-works` fails. Will debug.
> 
> On my local checkout the test passes. Are you sure that it's not the build server acting up?

`nix -L build .#checks.x86_64-linux.specialisation-works` definitely failed. I just double checked:

```
vm-test-run-specialisation-still-boot-under-secureboot> machine # Hash mismatch for kernel. Refusing to load!
vm-test-run-specialisation-still-boot-under-secureboot> machine # Failed to execute NixOS 23.05 (Stoat) (23.05 (Stoat)) (nixos-generation-1.efi) (\EFI\Linux\nixos-generation-1.efi): Security Policy Violation
```

@nikstur @RaitoBezarius If you have a fix, please push it to the branch, so we can merge this. I'm going to afk for the next week as well, but I can do code review.

**Comment by nikstur** [comment]
I can't replicate this. The test passes, even on a fresh checkout. There's something fishy going on here

**Comment by nikstur** [comment]
The thing I imagine that might happen is this: The kernel cannot be reproducibly hashed but has the same filename (the same nix input hash) So when the specialisation is generated with supposedly the same kernel (same filename) a different blake3 hash is produced and stored in the lanzaboote stub. The original stub (without specialisation) has the blake3 hash of the original kernel embedded while the specialisation stub has the new blake3 hash embedded. However, at this point there is only one kernel in` esp/EFI/nixos`, the one from the specialisation which has overridden the "original" kernel because it has the same filename. That's why the first boot in the test fails.

**Comment by nikstur** [comment]
[4d48331](https://github.com/nix-community/lanzaboote/pull/21/commits/4d48331676e7dba00bb7b8aea96c0b42cdb28e4f) seems to have fixed it. Now whenever a path already exists in the ESP, nothing is overwritten. This is also what  [system-boot-builder.py](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L83) does.

**Pull request merged**
