### PR TITLE
feat(flake): perform final fixups to the flake outputs

### PR DESCRIPTION
**Pull request by RaitoBezarius**
As flake-parts doesn't really support a concept of limited supported system (e.g. system for which we don't have CI), we need to fix up the final outputs to move the unsupported checks to another place where CI won't run them.

### CODE REVIEW

**Comment by blitz** [comment]
Hercules CI also succeeded after I massage it a bit. :-1:

**Review by blitz — APPROVED** [review]
I guess it's as good as it gets. :shrug: Better than the hanging jobs in the CI. But I feel there are feature requests here for both flake-parts and Hercules CI. :)

**Comment by RaitoBezarius** [comment]
@blitz Planning to send a PR to flake-parts for supporting the concept of "limited supported systems", but I fear this looks like a Flake limitation, like there's a whole to design here.

**Comment by nikstur** [comment]
> @blitz Planning to send a PR to flake-parts for supporting the concept of "limited supported systems", but I fear this looks like a Flake limitation, like there's a whole to design here.

Almost as if there should be a separation between default.nix and ci.nix ;)

**Comment by RaitoBezarius** [comment]
> > @blitz Planning to send a PR to flake-parts for supporting the concept of "limited supported systems", but I fear this looks like a Flake limitation, like there's a whole to design here.
> 
> Almost as if there should be a separation between default.nix and ci.nix ;)

well, default.nix should definitely have `ci = import ./ci.nix` :-). inchallah flake schemas happen fast enough…

**Pull request merged**
